In [1]:
import numpy as np

In [11]:
# 1a
a = np.zeros(10)
a[4] = 11
print(a)

[ 0.  0.  0.  0. 11.  0.  0.  0.  0.  0.]


In [16]:
# 1b
v = np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [17]:
# 1c
v = np.arange(10,50)
v_flip= np.flip(v,0)
print(v_flip)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [27]:
# 1d
m = np.matrix('0 1 2; 3 4 5; 6 7 8')
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [42]:
# 1e
a = np.asarray([1,2,0,0,4,0])
zero_indic = np.where(a == 0)[0]
print(zero_indic)

[2 3 5]


In [52]:
# 1f
r = np.random.rand(30)
print(r)
r_mean = r.mean()
print("\nMean of vector r is: " + str(r_mean))

[0.62194977 0.87327931 0.07764128 0.66783941 0.66566403 0.81262453
 0.64151858 0.59992176 0.1963714  0.72002177 0.32107257 0.34778629
 0.08347545 0.22872791 0.2136891  0.17635465 0.40435795 0.15723434
 0.22251374 0.69188345 0.92654918 0.95529365 0.25969388 0.11441595
 0.98113093 0.15741463 0.7998738  0.17392326 0.90899274 0.41555591]

Mean of vector r is: 0.48055904136488903


In [70]:
# 1g
x = np.ones((10,10))
x[1:-1,1:-1] = 0
#x[:,0] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [83]:
# 1h
x = np.ones((8,8))
x[0::2,0::2] = 0
x[1::2,1::2] = 0
#x[:,0] = 0
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [92]:
# 1i
t = np.array([[0,1],[1,0]])
#t = np.array([1,0])
x = np.tile(t,(4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [130]:
# 1j
z = np.arange(11)
ind1 = np.where(z < 8)[0]
ind2 = np.where(z > 3)[0]
ind = np.intersect1d(ind1,ind2)
print(z)
z[ind] *= -1
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [132]:
# 1k
Z = np.random.random(10)
print(Z)
Z = np.sort(Z)
print(Z)

[0.25759504 0.72120329 0.14933539 0.77851563 0.42211878 0.8100865
 0.80969502 0.48896204 0.77643703 0.82142945]
[0.14933539 0.25759504 0.42211878 0.48896204 0.72120329 0.77643703
 0.77851563 0.80969502 0.8100865  0.82142945]


In [134]:
# 1l
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.array_equal(A,B)
print(equal)

False


In [139]:
# 1m
Z = np.arange(10, dtype=np.int32)
print(Z.dtype)
Z = Z.astype(np.float32, copy=False) 
print(Z.dtype)
#for i in Z:
#    print(type(i))

int32
float32


In [142]:
# 1n
A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A,B)
D = np.diag(C)
#print(A)
#print(B)
print(C)
print(D)

[[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]
[ 18  66 132]
